### ISSUE TITLE
Mudder.js not strictly needed

### ISSUE THREAD

**Issue by fasiha** [adiwg/mdSpec#5]
Hi, I'm the author of Mudder.js and out of curiosity went to see how you were using it, at: https://github.com/adiwg/mdSpec/blob/76518a9647ad6749b62d3b7d82cabfc16da0f91c/app/pods/components/md-sidebar-list/item/component.js#L114-L116

I totally don't want to discourage you from using Mudder!, but if you're just doing base36 string/number conversions, you can actually use plain JavaScript:
```js
const stringToNumber = s => parseInt(s, 36);
const numberToString = n => n.toString(36);

[Mudder.base36.stringToNumber('ab12'), stringToNumber('ab12')]
// both evaluate to 480854

[Mudder.base36.numberToString(1234), numberToString(1234)]
// both evaluate to 'ya'
```
Feel free to close this if you plan on using Mudder for things other than base36, or if you're fine with the extra dependency (I am certainly happy that it's helpful!).

**Comment by jlblcc** [comment]
I'm actually using mudder.js to generate unique strings for persistent sorting in a drag-n-drop interface:

https://github.com/adiwg/mdSpec/blob/76518a9647ad6749b62d3b7d82cabfc16da0f91c/app/pods/components/md-sidebar-list/item/component.js#L119-L120

Mudder.js made this trivial to implement. I used the mudder base36 methods since they were available. Thanks for creating and releasing the library!

**Comment by fasiha** [comment]
Excellent! Thank you!
